from __future__ import annotations

from datetime import datetime, timezone
import json
from pathlib import Path
import tempfile
import unittest
import zipfile

from personal_state_mcp.history_import import inspect_history_export, parse_google_fit_takeout, parse_libreview_csv
from personal_state_mcp.storage import StateStore


LIBRE_CSV = """Glucose Data,Generated on,09-27-2026 10:00 AM UTC,Generated by,Test User
Device,Serial Number,Device Timestamp,Record Type,Historic Glucose mg/dL,Scan Glucose mg/dL
Libre 3,ABC123,09-25-2026 08:15 AM,0,112,
Libre 3,ABC123,09-25-2026 08:20 AM,1,,118
Libre 3,ABC123,bad timestamp,0,120,
"""


class HistoryImportTests(unittest.TestCase):
    def setUp(self) -> None:
        self.tmp = tempfile.TemporaryDirectory()
        self.root = Path(self.tmp.name)

    def tearDown(self) -> None:
        self.tmp.cleanup()

    def test_libreview_csv_parses_and_reports_rejections(self) -> None:
        path = self.root / "glucose.csv"
        path.write_text(LIBRE_CSV, encoding="utf-8")
        readings, preview = parse_libreview_csv(
            path,
            source_timezone="America/Los_Angeles",
            stored_at=datetime(2026, 9, 27, tzinfo=timezone.utc),
        )
        self.assertEqual([112, 118], [reading.value_mg_dl for reading in readings])
        self.assertEqual(["history", "scan"], [reading.sample_type for reading in readings])
        self.assertEqual(3, preview.rows_seen)
        self.assertEqual(2, preview.records_parsed)
        self.assertEqual(1, preview.records_rejected)
        self.assertEqual("2026-09-25T15:15:00Z", preview.first_measured_at)

    def test_historical_import_deduplicates_against_any_adapter(self) -> None:
        path = self.root / "glucose.csv"
        path.write_text(LIBRE_CSV, encoding="utf-8")
        readings, _ = parse_libreview_csv(path, source_timezone="America/Los_Angeles")
        store = StateStore(self.root / "state.db")
        first = store.import_glucose_readings(readings)
        second = store.import_glucose_readings(readings)
        self.assertEqual({"inserted": 2, "duplicates": 0}, first)
        self.assertEqual({"inserted": 0, "duplicates": 2}, second)

    def test_database_backup_is_a_readable_snapshot(self) -> None:
        path = self.root / "glucose.csv"
        path.write_text(LIBRE_CSV, encoding="utf-8")
        readings, _ = parse_libreview_csv(path, source_timezone="America/Los_Angeles")
        store = StateStore(self.root / "state.db")
        store.import_glucose_readings(readings)
        backup = store.backup_to(self.root / "state.backup.db")
        snapshot = StateStore(backup)
        self.assertEqual(2, snapshot.history_overview()["count"])

    def test_export_inspector_recognizes_takeout_directory(self) -> None:
        fit = self.root / "Takeout" / "Fit"
        fit.mkdir(parents=True)
        (fit / "Daily activity metrics.csv").write_text("Date,Steps\n", encoding="utf-8")
        preview = inspect_history_export(self.root)
        self.assertEqual("google_fit_takeout", preview.source)
        self.assertEqual(1, preview.files)

    def test_google_fit_takeout_parses_raw_daily_and_activity_data(self) -> None:
        archive_path = self.root / "takeout.zip"
        heart = {
            "Data Source": "heart",
            "Data Points": [
                {
                    "dataTypeName": "com.google.heart_rate.bpm",
                    "startTimeNanos": 1_700_000_000_000_000_000,
                    "endTimeNanos": 1_700_000_000_000_000_000,
                    "modifiedTimeMillis": 1_700_000_001_000,
                    "fitValue": [{"value": {"fpVal": 72}}],
                },
                {
                    "dataTypeName": "com.google.heart_rate.bpm",
                    "startTimeNanos": 1_700_000_060_000_000_000,
                    "endTimeNanos": 1_700_000_060_000_000_000,
                    "modifiedTimeMillis": 1_700_000_061_000,
                    "fitValue": [{"value": {"fpVal": 75}}],
                },
            ],
        }
        oxygen = {
            "Data Source": "oxygen",
            "Data Points": [
                {
                    "dataTypeName": "com.google.oxygen_saturation",
                    "startTimeNanos": 1_700_000_000_000_000_000,
                    "endTimeNanos": 1_700_000_000_000_000_000,
                    "fitValue": [{"value": {"fpVal": 97}}, {"value": {"fpVal": 0}}],
                }
            ],
        }
        sleep = {
            "Data Source": "sleep",
            "Data Points": [
                {
                    "dataTypeName": "com.google.sleep.segment",
                    "startTimeNanos": 1_700_000_000_000_000_000,
                    "endTimeNanos": 1_700_001_800_000_000_000,
                    "fitValue": [{"value": {"intVal": 4}}],
                },
                {
                    "dataTypeName": "com.google.sleep.segment",
                    "startTimeNanos": 1_700_001_800_000_000_000,
                    "endTimeNanos": 1_700_003_600_000_000_000,
                    "fitValue": [{"value": {"intVal": 5}}],
                },
            ],
        }
        daily = (
            "Start time,End time,Calories (kcal),Distance (m),Step count,Move Minutes count\n"
            "00:00:00.000-08:00,00:15:00.000-08:00,10,100,250,5\n"
            "00:15:00.000-08:00,00:30:00.000-08:00,12,120,300,7\n"
        )
        tcx = """<?xml version="1.0" encoding="UTF-8"?>
<TrainingCenterDatabase xmlns="http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2">
  <Activities><Activity Sport="Walking"><Id>2023-11-14T22:13:20Z</Id>
  <Lap StartTime="2023-11-14T22:13:20Z"><TotalTimeSeconds>600</TotalTimeSeconds></Lap>
  </Activity></Activities>
</TrainingCenterDatabase>"""
        with zipfile.ZipFile(archive_path, "w") as archive:
            archive.writestr(
                "Takeout/Fit/All Data/raw_com.google.heart_rate.bpm_com.sec.android.app.shealth_health_platform.json",
                json.dumps(heart),
            )
            archive.writestr(
                "Takeout/Fit/All Data/raw_com.google.oxygen_saturation_com.sec.android.app.shealth_health_platform.json",
                json.dumps(oxygen),
            )
            archive.writestr(
                "Takeout/Fit/All Data/raw_com.google.sleep.segment_com.sec.android.app.shealth_health_platform.json",
                json.dumps(sleep),
            )
            archive.writestr("Takeout/Fit/Daily activity metrics/2023-11-14.csv", daily)
            archive.writestr("Takeout/Fit/Activities/2023-11-14_Walking.tcx", tcx)

        records, preview = parse_google_fit_takeout(
            archive_path,
            imported_at=datetime(2026, 9, 27, tzinfo=timezone.utc),
        )
        self.assertEqual(1, preview.metric_counts["vitals.heart_rate"])
        self.assertEqual(1, preview.metric_counts["vitals.oxygen_saturation"])
        self.assertEqual(1, preview.metric_counts["sleep.session"])
        self.assertEqual(1, preview.metric_counts["activity.exercise_session"])
        heart_record = next(item for item in records if item.metric == "vitals.heart_rate")
        self.assertEqual([72.0, 75.0], [sample["value"] for sample in heart_record.payload["samples"]])
        steps = next(item for item in records if item.metric == "activity.steps")
        self.assertEqual(550, steps.payload["value"])
        self.assertEqual("google_fit_takeout", heart_record.adapter_id)

    def test_google_fit_import_is_idempotent(self) -> None:
        archive_path = self.root / "takeout.zip"
        payload = {
            "Data Source": "weight",
            "Data Points": [
                {
                    "dataTypeName": "com.google.weight",
                    "startTimeNanos": 1_700_000_000_000_000_000,
                    "endTimeNanos": 1_700_000_000_000_000_000,
                    "fitValue": [{"value": {"fpVal": 80.5}}],
                }
            ],
        }
        with zipfile.ZipFile(archive_path, "w") as archive:
            archive.writestr(
                "Takeout/Fit/All Data/raw_com.google.weight_com.google.android.apps.fitness_user_input.json",
                json.dumps(payload),
            )
        records, _ = parse_google_fit_takeout(archive_path)
        store = StateStore(self.root / "state.db")
        self.assertEqual({"inserted": 1, "duplicates": 0}, store.import_health_observations(records))
        self.assertEqual({"inserted": 0, "duplicates": 1}, store.import_health_observations(records))


if __name__ == "__main__":
    unittest.main()
